apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: harryspace
    user: user
    password: password
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
